apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: landing-page
build:
  artifacts:
  - image: happylou/landing-page
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - k8s/*
deploy:
  kubectl: {}