apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: landing-page
build:
  tagPolicy:
    sha256: {} # latest
  artifacts:
  - image: happylou/landing-page
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
    - k8s/kustomization.yaml
deploy:
  kubectl: {}