apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: landing-page
build:
  artifacts:
    - image: happylou/landing-page
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/ingress.yaml
      - k8s/namespace.yaml