apiVersion: v1
kind: Service
metadata:
  name: landing-page
  namespace: happylou
spec:
  ports:
    - port: 3000
  type: ClusterIP
  selector:
    app: landing-page
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  namespace: happylou
spec:
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
        - name: landing-page
          image: happylou/landing-page
          ports:
            - containerPort: 3000
